# # storage class 

# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: ebs-sc
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
#   fsType: ext4
#   encrypted: "true"
# volumeBindingMode: WaitForFirstConsumer

# ---
# persistent volume claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins-ns
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
