apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: jenkins-ns
type: Opaque
data:
  config.json: ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJhdXRoIjogImFXSnliV3B1Ylc5eWEybGtZWFJsTDVKRFlpVXlKVG5yV2pKUlJVUlpTWFJ2ZFdSMVlYZHZiM05oYkdodk9rUUtJREV6IgogICAgICB9CiAgICB9Cn0K
