apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: jenkins-ns
type: Opaque
data:
  config.json: ewogICAgYXV0aHM6IHsKICAgICAgaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvOiB7CiAgICAgICAgYXV0aDogYVdKeVlXaHBiVzF2YUdGdFpXUjZZV2RvYkc5MWJEbzVPU1V6YTFveVVTVkVTR1ZrZWdvPQogICAgICB9CiAgICB9CiAgfQo=